# Generated by Django 5.2.3 on 2025-06-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_type', models.CharField(choices=[('organic', 'Organic Certification'), ('quality', 'Quality Assurance'), ('safety', 'Food Safety'), ('fair_trade', 'Fair Trade'), ('other', 'Other')], max_length=20)),
                ('certification_name', models.CharField(max_length=200)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_document', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('verification_url', models.URLField(blank=True, help_text='URL to verify certificate online')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('transaction_type', models.CharField(choices=[('list_produce', 'List Produce'), ('buy_produce', 'Buy Produce'), ('other', 'Other')], max_length=20)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('value_wei', models.BigIntegerField(default=0)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('gas_price', models.BigIntegerField(blank=True, null=True)),
                ('produce_id', models.IntegerField(blank=True, null=True)),
                ('produce_name', models.CharField(blank=True, max_length=200)),
                ('network', models.CharField(default='sepolia', max_length=20)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='farmdetails',
            name='farm_address',
            field=models.TextField(blank=True, help_text='Physical address of the farm'),
        ),
        migrations.AddField(
            model_name='farmdetails',
            name='farm_description',
            field=models.TextField(blank=True, help_text='Description of the farm'),
        ),
        migrations.AddField(
            model_name='farmdetails',
            name='farm_image',
            field=models.ImageField(blank=True, null=True, upload_to='farm_images/'),
        ),
        migrations.AddField(
            model_name='farmdetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmdetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddIndex(
            model_name='farmdetails',
            index=models.Index(fields=['latitude', 'longitude'], name='users_farmd_latitud_2a1513_idx'),
        ),
        migrations.AddIndex(
            model_name='farmdetails',
            index=models.Index(fields=['organic_certified'], name='users_farmd_organic_8bf57c_idx'),
        ),
        migrations.AddField(
            model_name='certification',
            name='farm_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='users.farmdetails'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['certification_type'], name='users_certi_certifi_9efc46_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['is_active'], name='users_certi_is_acti_dd52bc_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['transaction_hash'], name='users_trans_transac_3bce0c_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['user_profile', '-timestamp'], name='users_trans_user_pr_2f2195_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['transaction_type'], name='users_trans_transac_926861_idx'),
        ),
    ]
