# Generated by Django 5.2.3 on 2025-06-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('transaction_type', models.CharField(choices=[('list_produce', 'List Produce'), ('buy_produce', 'Buy Produce')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('gas_used', models.PositiveIntegerField(blank=True, null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('value', models.DecimalField(decimal_places=0, default=0, help_text='Value in wei', max_digits=20)),
                ('produce_id', models.PositiveIntegerField(blank=True, help_text='Related produce ID', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_hash'], name='blockchain__transac_697a0b_idx'), models.Index(fields=['status'], name='blockchain__status_096a5b_idx'), models.Index(fields=['produce_id'], name='blockchain__produce_43ac66_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('ProduceListed', 'Produce Listed'), ('ProduceSold', 'Produce Sold')], max_length=50)),
                ('transaction_hash', models.CharField(max_length=66)),
                ('block_number', models.PositiveIntegerField()),
                ('log_index', models.PositiveIntegerField()),
                ('event_data', models.JSONField(help_text='Raw event data from blockchain')),
                ('produce_id', models.PositiveIntegerField(blank=True, null=True)),
                ('farmer_address', models.CharField(blank=True, max_length=42)),
                ('buyer_address', models.CharField(blank=True, max_length=42)),
                ('block_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-block_number', '-log_index'],
                'indexes': [models.Index(fields=['event_name'], name='blockchain__event_n_d114e1_idx'), models.Index(fields=['produce_id'], name='blockchain__produce_72af93_idx'), models.Index(fields=['block_number'], name='blockchain__block_n_b79159_idx')],
                'unique_together': {('transaction_hash', 'log_index')},
            },
        ),
    ]
