# Generated by Django 5.2.3 on 2025-06-19 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Produce Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_id', models.PositiveIntegerField(help_text='ID from smart contract', unique=True)),
                ('contract_address', models.CharField(help_text='Smart contract address', max_length=42)),
                ('name', models.CharField(help_text='Name of the produce', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity in kg or units')),
                ('price_per_unit', models.DecimalField(decimal_places=0, help_text='Price per unit in wei', max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=0, help_text='Total price in wei', max_digits=20)),
                ('farmer_address', models.CharField(help_text="Farmer's wallet address", max_length=42)),
                ('buyer_address', models.CharField(blank=True, help_text="Buyer's wallet address", max_length=42, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('listed_timestamp', models.DateTimeField(help_text='When produce was listed on blockchain')),
                ('sold_timestamp', models.DateTimeField(blank=True, help_text='When produce was sold', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_produce', to=settings.AUTH_USER_MODEL)),
                ('farmer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_produce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProduceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produce_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produce.produce')),
            ],
        ),
        migrations.AddIndex(
            model_name='produce',
            index=models.Index(fields=['blockchain_id'], name='produce_pro_blockch_bbffbd_idx'),
        ),
        migrations.AddIndex(
            model_name='produce',
            index=models.Index(fields=['farmer_address'], name='produce_pro_farmer__6fafca_idx'),
        ),
        migrations.AddIndex(
            model_name='produce',
            index=models.Index(fields=['is_sold'], name='produce_pro_is_sold_6325d9_idx'),
        ),
    ]
